<?php
include ("header.php");
?>


<section class="inner-intro bg-1 bg-overlay-black-70" style="background:url">
  <div class="container">
     <div class="row text-center intro-title">
           <div class="col-md-6 text-md-right float-right">
             <ul class="page-breadcrumb">
                <li><a href="index.php"><i class="fa fa-home"></i> Home</a> <i class="fa fa-angle-double-right"></i></li>
                <li><span>Terms of use</span> </li>
             </ul>
           </div>
     </div>
  </div>
</section>

 <section class="service-center white-bg page-section-ptb">
 <div class="container">
   <div class="row">
     <div class="col-md-12">
       <center><h1>TERMS OF USE</h1></center>         
        <p>Welcome to the Carcentive Website.  Please read these terms and conditions carefully.  By your use of this Website, you agree to be bound by and comply with the terms and conditions below.  These terms and conditions are subject to change without notice, from time to time in our sole discretion.  We will notify you of amendments to these terms and conditions by posting them to this Website.  If you do not agree with these terms and conditions, please do not access or use this Website.</p>
        <h4>Disclaimer of Warranty</h4>
        <p>ALL CONTENT, MATERIALS, PRODUCTS, SERVICES AND INFORMATION MADE AVAILABLE ON OR THROUGH THIS WEBSITE ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS, WITHOUT REPRESENTATIONS, WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.  AS SUCH, YOUR USE OF THIS WEBSITE IS AT YOUR OWN RISK.  SUBJECT TO THE FOREGOING, CARCENTIVE DISCLAIMS ALL IMPLIED WARRANTIES INCLUDING, WITHOUT LIMITATION, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND ALL EXPRESS WARRANTIES EXCEPT THOSE EXPLICITLY MADE IN THESE TERMS AND CONDITIONS. CARCENTIVE MAKES NO REPRESENTATION THAT THE INFORMATION OR CONTENT CONTAINED ON THIS WEBSITE, YOUR RESULTS IN USING THIS WEBSITE, OR THE SERVICE ITSELF WILL BE ACCURATE, VALID, RELIABLE, COMPLETE, TIMELY OR AVAILABLE OR THAT IT DOES NOT VIOLATE OR INFRINGE THE RIGHTS OF ANY THIRD PARTY. CARCENTIVE DOES NOT WARRANT THAT THE CONTENT, MATERIALS, PRODUCTS, SERVICES AND INFORMATION MADE AVAILABLE TO YOU THROUGH THIS WEBSITE, THEIR SERVERS, OR E-MAIL SENT FROM CARCENTIVE WILL BE UNINTERRUPTED, ERROR FREE, FREE OF VIRUSES OR OTHER HARMFUL AGENTS OR COMPONENTS, SECURE OR TIMELY. CARCENTIVE MAKES NO REPRESENTATION AND SPECIFICALLY DISCLAIMS ANY WARRANTY REGARDING ANY SITE LINKED TO THIS WEBSITE. CARCENTIVE DOES NOT WARRANT, GUARANTEE OR ENSURE THE QUALITY OF ANY PRODUCT OR SERVICE PROVIDED BY ANY AFFILIATE OR MERCHANT.

THIS DISCLAIMER BY CARCENTIVE IN NO WAY AFFECTS THE TERMS OF ANY MANUFACTURER’S OR THIRD PARTY SELLER’S WARRANTY, IF ANY, RELATED TO THE GOODS PURCHASED VIA THIS WEBSITE.  TITLE TO GOODS AND MERCHANDISE IS RETAINED BY THE SELLER UNTIL THE GOODS AND MERCHANDISE ARE PAID FOR BY THE PURCHASER, AT WHICH TIME TITLE PASSES TO THE PURCHASER.  

CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MIGHT HAVE ADDITIONAL RIGHTS.
</p>
<h4>Limitation of Liability</h4>
<p>YOU AGREE THAT, EXCEPT AS OTHERWISE PROVIDED UNDER APPLICABLE LAWS, NEITHER CARVCENTIVE NOR ITS AFFILIATES, NOR THE DIRECTORS, OFFICERS, OWNERS, EMPLOYEES, AGENTS, CONTRACTORS, REPRESENTATIVES, SUCCESSORS OR ASSIGNS OF EACH, SHALL BE LIABLE FOR ANY DAMAGES WHATSOEVER ARISING OUT OF OR RELATED TO THE USE OF, ACCESS TO, RELIANCE ON, OR INABILITY TO USE, THIS WEBSITE OR ANY OTHER WEBSITE LINKED TO THIS WEBSITE.  THIS WAIVER OF LIABILITY APPLIES TO DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, PUNITIVE, EXEMPLARY, STATUTORY OR OTHER DAMAGES YOU OR OTHERS MAY SUFFER, AS WELL AS DAMAGES FOR LOST PROFITS, LOST REVENUE, LOST GOODWILL, BUSINESS INTERRUPTION OR THE LOSS OF DATA OR INFORMATION, EVEN IF CARVENTIVE IS NOTIFIED IN ADVANCE OF THE POTENTIAL FOR ANY SUCH DAMAGES AND REGARDLESS OF THE FORM OF ACTION, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE), WARRANTY, STRICT OR PRODUCT LIABILITY OR OTHERWISE.</p>
<h4>Trademarks and Copyrights</h4>
<p>You agree that all content appearing on this Website including, but not limited to, code, trademarks, service marks, trade names, graphics, images, text, audio clips, button icons, digital downloads, data compilations and computer software are the sole property of Carcentive or its partners and suppliers, and protected by United States and international copyright laws.  The compilation of all content on this Website is the exclusive property of Carcentive and protected by United States and international laws.  All software used on this site is the property of Carcentive or its software suppliers and protected by United States and international copyright laws.  Users are granted permission to browse and use the Carcentive Website for its intended purpose, which is for your use only as a consumer or dealer.  Any other use including, but not limited to, the reproduction, duplication, modification, distribution, sale, transmission, republication, removal, deletion, addition, framing, display, or performance of the content on this Website or the exploitation in any other manner of any of the content of this Website, in part or in whole, is strictly prohibited.  Except as expressly authorized in writing, the use or misuse of any trademarks, service marks, trade names, logos, text, images, graphics, intellectual property or content from this Website is strictly prohibited. 

Carcentive does not grant, by implication or otherwise, any license or right to use any trademark, service mark, trade name or logo, or the content displayed on this Website, without the prior written consent of Carcentive.  Carcentive prohibits the use of the Carcentive logo or other proprietary graphics or trademarks as a link to any Website unless the creation of such a link is approved in advance, and in writing, by Carcentive.  Registered and unregistered proprietary information is owned and held by Carcentive and its licensors and, therefore, you may be liable for infringement or misappropriation or other legal action to the fullest extent of the law if you misuse this Website in any form, either mentioned or unmentioned. 

Carcentive is a trademark or trade dress in the United States and/or other countries.  Carcentive’s trademarks and trade dress may not be used in connection with any product or service that is not Carcentive’s, in any manner that is likely to cause confusion among customers, or in any manner that disparages or discredits Carcentive.  All other trademarks not owned by Carcentive that appear on this Website are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by, Carcentive.</p>
<h4>Third Party Websites</h4>
<p>You agree that Carcentive encourages you to exercise discretion browsing the internet.  Our Website, products or services may direct you to sites containing information that some people may find offensive or inappropriate.  Any such link is provided solely as a convenience to you. Carcentive and its affiliates make no representation or warranty about the legality of any third party Website nor about its accuracy, content, products or services.  Any such Website is independent from Carcentive, and Carcentive has no control over, or responsibility with respect to, the information provided or activities undertaken by any such Website.  A link between Carcentive and another Website further does not mean that Carcentive endorses, recommends, sponsors or approves that Website.  Linking to off-site pages is done at your own risk, requiring you to make your own independent decisions regarding your interactions or communications with any other Website. Carcentive expressly disclaims any responsibility or liability for any damage, loss, or injury arising out of the activities of any third party, the goods or services offered or the content displayed by any such third party not under the Carcentive domain.  </p>
<h4>Use Restrictions</h4>
<p>You agree that you will not use this Website for certain commercial or political purposes including, but not limited to, advertising or soliciting funds; to monitor, gather or copy content on this Website by using any robot, “bot”, spider, crawler, spyware, engine, device, software, extraction tool, or any other automatic device, utility or manual process of any kind; to frame or utilize framing techniques to enclose any trademark or other proprietary information including, but not limited to, any images, text, or page layout; to use any meta tags or any other “hidden text” utilizing Carcentive’s name or any trademarks; to engage in any activity that interferes with a user’s access to the Website or the proper operation of this Website.  You may not modify, reproduce, duplicate, copy, distribute, sell, resell, publish, license, visit or otherwise exploit this Website for any commercial purpose.  You also agree that in using this Website you will not impersonate any person or entity.</p>
<h4>Unlawful Conduct</h4>
<p>You agree that you are prohibited from posting or transmitting to the Carcentive Website any unlawful, threatening, libelous, defamatory, obscene, scandalous, inflammatory, pornographic or profane material, or any other material that could give rise to any civil or criminal liability under the law, as well as anything in contravention of these Terms and Conditions.  Carcentive reserves the right to seek all remedies available at law and in equity for violations of these Terms and Conditions, including the right to block access from a particular internet address to this Website.</p>
<h4>Termination of Use of This Website</h4>
<p>You agree that any violation of these Terms and Conditions, the unauthorized use of this Website, content materials and intellectual property as well as any fraudulent, abusive or otherwise illegal activity shall be grounds for termination of your right to access, browse and use this Website. Carcentive reserves the right to terminate or suspend your access to this Website and its content and use at any time, with or without notice, at Carcentive’s discretion.  Should your access to this Website be terminated, you are prohibited from accessing this Website under a new name unless expressly invited to do so by Carcentive</p>
<h4>Product Descriptions</h4>
<p>Carcentive attempts to be as accurate as possible.  However, Carcentive does not warrant that product descriptions or other content of this Website is accurate, complete, reliable, current or error free.  If a product offered through Carcentive is not as described, your sole remedy is to return it in unused condition.</p>
<h4>Limited Availability and Price</h4>
<p>In the event a product or service is listed at an incorrect price due to a typographical error or an error in pricing information received from a third party, Carcentive shall have the right to refuse or cancel any orders placed for product or service listed at the incorrect price. Carcentive shall have the right to limit the number of items purchased through this Website. Carcentive shall have the right to refuse or cancel any order whether or not the order has been confirmed and your credit card charged.  If your credit card has already been charged for the purchase and your order is cancelled, Carcentive shall immediately request that the seller issue a credit to your credit card account in the amount of the charge.</p>
<h4>Revisions</h4>
<p>Carcentive may, in its sole discretion, and with or without notice to you, make changes to, or discontinue, any aspect of this Website including, without limitation, any content, products, services or prices offered through this Website. Carcentive shall not be liable to you or any third party should it exercise this right to modify or discontinue this Website. Carcentive also reserves the right to revise, at its sole and absolute discretion, the Terms and Conditions of this Website at any time.  All revisions will be posted on these Terms and Conditions and will be effective immediately upon its posting.  By surfing, using, browsing or purchasing on this Website, you are deemed notified and bound by any changes to these Terms and Conditions.  We encourage users to review these Terms and Conditions each time you visit this Website to remain informed of any changes to them.</p>
<h4>Electronic Communications</h4>
<p>When you visit this Website or send e-mails to us, you are communicating with us electronically.  You consent to receive communications from us electronically.  You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.</p>
<h4>Consent</h4>
<p>By accessing, browsing and/or using this Website, you acknowledge that you have read, understood and agree to be bound by these Terms and Conditions and you agree to comply with all applicable laws and regulations.  If you do not agree to these terms then please do not use this Website.</p>
<h4>Privacy Policy</h4>
<p>The privacy of those who visit our Website is of primary concern to Carcentive.  We adhere to the highest ethical standards of the industry.  By using this Website, you agree that you have reviewed and accepted our privacy policy.  We automatically gather some data from everyone who visits our Website, while other information is obtained at the discretion of the individual.  Our sole purpose in doing this is to enhance the experience of individual visitors to our Website.  None of this information is shared with outside parties other than companies we employ to perform functions on our behalf, to whom limited data is given as is necessary in order to complete a transaction or to maintain our relationship with you.</p>
<h4>Cookies</h4>
<p>Carcentive reserves the right to store information on your computer in the form of a cookie or similar file for purposes of modifying this Website to reflect your preferences.  Cookies allow us to respond to you as an individual, thus allowing us to personalize, customize and quickly process and complete your experience without having to continually request the same basic information from you.  Cookies do not give us access to your computer or any information about you, other than the data which you choose to share with us, and are not used to store any personal information such as name, address or payment information.</p>
<h4>Disclosure to Authorities</h4>
<p>Carcentive cannot guarantee that all private communications and other personally identifiable information will never be disclosed in ways not otherwise described in these Terms and Conditions.  We reserve the right, and may be forced, to disclose any and all information to government bodies or government officials or third parties under certain circumstances or third parties may unlawfully intercept or access transmissions or private communications.  As such, you authorize Carcentive to disclose any and all information about you to law enforcement or other government officials as we, in our sole discretion, believe necessary or appropriate, in connection with any investigation of fraud, intellectual property infringements or other activity that is, or may be, illegal or that may expose Carcentive to legal liability.
</p>
<h4>Indemnification</h4>
<p>You agree to indemnify, defend and hold harmless Carcentive, its affiliates, subsidiaries, officers, directors, owners, employees, agents, contractors, licensors and licensees, representatives, successors or assigns, from all damages, liabilities, costs and expenses, including reasonable attorneys’ fees, on account of any claim, suit, action, demand or proceeding made or brought against any such party, or on account of the investigation, defense or settlement thereof, arising in connection with your use of this Website.</p>
<h4>Enforceability, Governing Law and Jurisdiction</h4>
<p>These Terms and Conditions constitute the entire agreement between you and Carcentive.  In the event that any of the terms or provisions of these Terms and Conditions shall be held by a court of competent jurisdiction to be unenforceable, then such terms or provisions shall be construed, as nearly as possible, to reflect the intentions of the parties with the other terms and provisions remaining in full force and effect.

Your access to and use of this Website, and these Terms and Conditions, are governed and construed in accordance with the laws of the State of  New Jersey, without regard to its conflicts of law provisions.  Any action against Carcentive arising from, or relating to, your access to and use of this Website and the provisions of these Terms and Conditions must be brought by you exclusively in the state and federal courts located in Essex County, State of New Jersey.  You consent and submit to the exclusive personal jurisdiction and venue of the state and federal courts located in Essex County, State of  New Jersey, for the adjudication of all claims by Carcentive against you arising from, or relating to, your access to and use of this Website and the provisions of these Terms and Conditions.  You agree to waive any and all objections that you may have to New Jersey law as the governing law and to the sole and exclusive venue being Essex County, New Jersey.  If you do not agree to these terms then you must immediately cease using this Website and its services.  Your continuing to use this Website and its services will constitute your consent to these terms. 

Carcentive’s failure to exercise or enforce any right or provision of these Terms and Conditions shall not constitute a waiver of such right or provision unless acknowledged and agreed to by Carcentive in writing.  You acknowledge and agree that you will not seek to litigate any claims against Carcentive or any of its affiliates on a class action or representative party basis and that you shall pursue such claims solely on an individual basis.
</p>
<h4>Limitations on Actions</h4>
<p>Any action concerning any dispute that you may have with respect to, arising out of, or in connection with this Website must be commenced within one (1) year after the cause of the dispute first arises, and your failure to do so will permanently bar any cause of action that you may have.</p>
<h4>Your Representations</h4>
<p>You represent that you are 18 years of age or older and that you are not under any legal or other disability which limits your ability to comply with these Terms and Conditions.</p>
    </div>
   </div>
  </div>
</section>

<?php
include ("footer.php");
?>